# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
os:
  - osx
  - linux
language: R
r: bioc-release
sudo: false
cache: packages
warnings_are_errors: false
bioc_packages: 
  - GenomicRanges
  - BSgenome
branches: 
  only:
  - master
  - dev
r_build_args: "--no-build-vignettes"
r_check_args: "--no-vignettes"
after_success:
  - Rscript -e 'covr::codecov()'